### ISSUE TITLE
What is the difference between the goals of gcp4s and googleapis-http4s-runtime?

### ISSUE THREAD

**Issue by i10416** [armanbilge/gcp4s#268]
There are two GCP-related projects; googleapis-http4s(-runtime) and this repository.

I found there are some overlaps and slightly different but almost the same implementation between these projects.

Is gcp4s supposed to be a wrapper for googleapis in the same way [firestore-rs](https://github.com/abdolence/firestore-rs) provides richer APIs over underlying [gcloud-sdk-rs](https://github.com/abdolence/gcloud-sdk-rs/)(auto-generated from google proto files and openapi schema) or is gcp4s yet another googleapis-http4s-runtime?

https://github.com/davenverse/googleapis-http4s-runtime looks still WIP, but separating manual implementation(e.g. auth middleware) from auto-generated API clients seems better design. Perhaps, is there ongoing effort to migrate authentication stuffs to http4s-googleapis-runtime?

It is nice to be able to access GCP using Typelevel stack, so I'm happy to contribute whichever project.

**Comment by armanbilge** [comment]
> Perhaps, is there ongoing effort to migrate authentication stuffs to http4s-googleapis-runtime?

Yes, that's correct. I wanted to migrate the authentication code from gcp4s to http4s-googleapis-runtime and add support for Scala Native.

I also want to add support for HTTP APIs to http4s-googleapis thanks to https://github.com/armanbilge/gcp4s/issues/254.

> Is gcp4s supposed to be a wrapper for googleapis

This is an old project, that pre-dates HTTP/2 and gRPC support in Ember, otel4s superseding Natchez, and Scala Native support in the Typelevel stack. Probably we can sunset it.

**Comment by i10416** [comment]
Thank you for quick response!
I'will send some PRs to googleapis-http4s projects!
